# Generated by Django 4.2.11 on 2024-07-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_user_all_data_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_all_data',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='HomePage/media'),
        ),
    ]
